spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/secondproject
    username: team_c
    password: green502
# mybatis config
mybatis:
  type-aliases-package: com.green.secondproject
  mapper-locations: classpath:mapper/**/*.xml
# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

my-api:
  key: 9a7b0b8f560b480abf0d0cb941af2bea
